(dp1
S'output'
p2
S'The "end" tag is unmatched, please check if you have a starting "block" tag'
p3
sS'layer'
p4
S'ParserContainer'
p5
sS'code'
p6
S'{{left_sidebar_enabled= False}}\n{{right_sidebar_enabled=True}}\n\n{{extend \'layout.html\'}}\n\n{{block center}}\n\n<div class="video_frame" id="youtube_video_frame" >\n    <object width="640" height="360">\n      <param name="movie" value="https://www.youtube.com/v/{{=video.youtube_video_id}}?version=3"></param>\n      <param name="allowFullScreen" value="true"></param>\n      <param name="allowScriptAccess" value="always"></param>\n      <embed src="https://www.youtube.com/v/{{=video.youtube_video_id}}?version=3" type="application/x-shockwave-flash" allowfullscreen="true" allowScriptAccess="always" width="640" height="360"></embed>\n    </object>\n</div>\n\n{{try:}}\n    <ul>\n    {{for a in annotations:}}\n        <li>\n        {{=a.video_time}} {{a.comment}}\n        </li>\n    {{end}}\n    </ul>\n{{except:}}\n{{pass}}\n\n{{end}}\n\n{{block right_sidebar}}\n    {{=annotation_form}}\n{{end}}\n'
p7
sS'snapshot'
p8
(dp9
S'exception'
p10
(dp11
S'__module__'
p12
S"'socket'"
p13
sS'__getslice__'
p14
S"<method-wrapper '__getslice__' of error object>"
p15
sS'__str__'
p16
S"<method-wrapper '__str__' of error object>"
p17
sS'__reduce__'
p18
S'<built-in method __reduce__ of error object>'
p19
sS'__dict__'
p20
S'{}'
p21
sS'__sizeof__'
p22
S'<built-in method __sizeof__ of error object>'
p23
sS'__weakref__'
p24
S'None'
p25
sS'__init__'
p26
S"<method-wrapper '__init__' of error object>"
p27
sS'__setattr__'
p28
S"<method-wrapper '__setattr__' of error object>"
p29
sS'__reduce_ex__'
p30
S'<built-in method __reduce_ex__ of error object>'
p31
sS'__new__'
p32
S'<built-in method __new__ of type object>'
p33
sS'errno'
p34
S'11'
p35
sS'__format__'
p36
S'<built-in method __format__ of error object>'
p37
sS'__class__'
p38
S"<class 'socket.error'>"
p39
sS'filename'
p40
S'None'
p41
sS'__doc__'
p42
S'None'
p43
sS'__getitem__'
p44
S"<method-wrapper '__getitem__' of error object>"
p45
sS'__setstate__'
p46
S'<built-in method __setstate__ of error object>'
p47
sS'__getattribute__'
p48
S"<method-wrapper '__getattribute__' of error object>"
p49
sS'args'
p50
S"(11, 'Resource temporarily unavailable')"
p51
sS'__subclasshook__'
p52
S'<built-in method __subclasshook__ of type object>'
p53
sS'__unicode__'
p54
S'<built-in method __unicode__ of error object>'
p55
sS'strerror'
p56
S"'Resource temporarily unavailable'"
p57
sS'__delattr__'
p58
S"<method-wrapper '__delattr__' of error object>"
p59
sS'__repr__'
p60
S"<method-wrapper '__repr__' of error object>"
p61
sS'__hash__'
p62
S"<method-wrapper '__hash__' of error object>"
p63
ssS'evalue'
p64
S'[Errno 11] Resource temporarily unavailable'
p65
sS'frames'
p66
(lp67
(dp68
S'file'
p69
S'/home/leo/projects/heroku_projects/annotatit/venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py'
p70
sS'dump'
p71
(dp72
S'client'
p73
S'<socket._socketobject object>'
p74
sS'sock'
p75
S'<gunicorn.sock.TCPSocket object>'
p76
sS'addr'
p77
S"('127.0.0.1', 34614)"
p78
sS'sock.accept'
p79
S'<bound method _socketobject.accept of <socket._socketobject object>>'
p80
ssS'lnum'
p81
I39
sS'lines'
p82
(dp83
I34
S"            # select which is where we'll wait for a bit for new"
p84
sI35
S'            # workers to come give us some love.'
p85
sI36
S''
sI37
S'            for sock in ready:'
p86
sI38
S'                try:'
p87
sI39
S'                    client, addr = sock.accept()'
p88
sI40
S'                    client.setblocking(1)'
p89
sI41
S'                    util.close_on_exec(client)'
p90
sI42
S'                    self.handle(sock, client, addr)'
p91
sI43
S''
ssS'call'
p92
S'(self=<gunicorn.workers.sync.SyncWorker object>)'
p93
sS'func'
p94
S'run'
p95
sa(dp96
g69
S'/usr/lib/python2.7/socket.py'
p97
sg71
(dp98
S'self._sock'
p99
S'<socket object, fd=6, family=2, type=1, protocol=0>'
p100
sS'self'
p101
S'<socket._socketobject object>'
p102
sS'sock'
p103
S'undefined'
p104
sS'addr'
p105
g104
sS'self._sock.accept'
p106
S'<built-in method accept of _socket.socket object>'
p107
ssg81
I202
sg82
(dp108
I197
S'        for method in _delegate_methods:'
p109
sI198
S'            setattr(self, method, dummy)'
p110
sI199
S'    close.__doc__ = _realsocket.close.__doc__'
p111
sI200
S''
sI201
S'    def accept(self):'
p112
sI202
S'        sock, addr = self._sock.accept()'
p113
sI203
S'        return _socketobject(_sock=sock), addr'
p114
sI204
S'    accept.__doc__ = _realsocket.accept.__doc__'
p115
sI205
S''
sI206
S'    def dup(self):'
p116
ssg92
S'(self=<socket._socketobject object>)'
p117
sg94
S'accept'
p118
sasS'pyver'
p119
S'Python 2.7.3: /home/leo/projects/heroku_projects/annotatit/venv/bin/python (prefix: /home/leo/projects/heroku_projects/annotatit/venv)'
p120
sS'etype'
p121
S"<class 'socket.error'>"
p122
sS'date'
p123
S'Tue Apr 23 11:26:38 2013'
p124
sS'locals'
p125
(dp126
S'self'
p127
S'<socket._socketobject object>'
p128
sssS'traceback'
p129
S'Traceback (most recent call last):\n  File "/home/leo/projects/heroku_projects/annotatit/venv/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 39, in run\n    client, addr = sock.accept()\n  File "/usr/lib/python2.7/socket.py", line 202, in accept\n    sock, addr = self._sock.accept()\nerror: [Errno 11] Resource temporarily unavailable\n'
p130
s.